# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - url: https://direct2.rammerhead.org/
  - url: https://direct.rammerhead.org/
  - url: https://ram.thefemboy.gay/
  - url: https://browser.rammerhead.org/
  - url: https://rammerhead.midnightofficial.xyz/
  - url: https://a.midnightofficial.xyz/
  - url: https://r.midnightofficial.xyz/
  - url: https://e.midnightofficial.xyz/
  - url: https://rh.midnightofficial.xyz/
  - url: https://r.lucidofficial.xyz/
  - url: https://r.apexhcf.xyz/
  - url: https://r.kahoot.click/
  - url: https://r.pyro.bar/
  - url: https://sso.prodigygame.online/
  - url: https://rm.triway.live/
  - url: https://afsgderdfegtdfsewrdfserdgcvxdsfegrfbcv.ruralanemone.tech/
  - url: https://yee.ruralanemone.tech/
  - url: https://xmr.luph.cc/
  - url: https://use.matrix.luph.lol/
  - url: https://r.generalmathematics.net/
  - url: https://legit.studyschooltoday.eu.org/
  - url: https://sussybaka.studyschooltoday.eu.org/
  - url: https://pickmysubdomaininchat.studyschooltoday.eu.org/
  - url: https://my.name.is.john.cenaa.studyschooltoday.eu.org/
  - url: https://r.utopia.education/
  - url: https://r.utopiaunblocker.org/
  - url: https://r.utopiaworld.ink/
  - url: https://rh.aluminumnetwork.xyz/
  - url: https://r.aluminumnetwork.xyz/
  - url: https://r.weeb-central.icu/
  - url: https://direct.weeb-central.icu/
  - url: https://rh.weeb-central.icu/
  - url: https://ram.weeb-central.icu/
  - url: https://sso.weeb-central.icu/
  - url: https://r.studyschooltoday.eu.org/
  - url: https://desp.icable.me/
  - url: https://bananaboat.me/
  - url: https://rammer.camdvr.org/
  - url: https://rammer.ooguy.com/
  - url: https://rammer.giize.com/
  - url: https://rammer.loseyourip.com/
  - url: https://rh.titannetwork.info/
  - url: https://empowerlearning.titannetwork.info/
  - url: https://enrichingstudents.titannetwork.info/
  - url: https://googleclassroom.titannetwork.info/
  - url: https://cloudflare.rammerhead.org/
  - url: https://rammerhead.morrowseer.xyz/
  - url: https://poodle.xn--unup4y/
  - url: https://rx.blackxfiied.xyz/
  - url: https://ram.motortruck1221.tech/
  - url: https://rh.motortruck1221.me/
  - url: https://rd.globalcentauri.tech/
  - url: https://ramming.xan.lol/
  - url: https://rh.naruto.tech/
  - url: https://pwoxywoxy.xan.lol/
  - url: https://rh.lhost.dev/
  - url: https://chrome.lhost.dev/
  - url: https://blocked.lhost.dev/
  - url: https://tabs.lhost.dev/
  - url: https://r.willuna.live/
  - url: https://direct3.rammerhead.org/
  - url: https://rh.lwaid.dev/
  - url: https://direct4.rammerhead.org/
  - url: https://direct5.rammerhead.org/
  - url: https://rammerhead.yitzib.me/
  - url: https://not.my.actual.name.yitzib.me/
  - url: https://r.yitzib.me/
  - url: https://im.not.r.aci.st/
  - url: https://breadtw.ink/
  - url: https://against.the.gra.im/
  - url: https://r.il.ax/
  - url: https://link2.viewdns.net/
  - url: https://rammerhead.izooc.ninja/
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /rammerhead-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Rammerhead Uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
